services:
  - type: web
    name: mydownloader
    env: docker
    plan: free
    region: singapore
    repo: https://github.com/azhar0407/mydownloader
    branch: main
    autoDeploy: true
    healthCheckPath: /health
